# fly.toml app configuration file generated for melted-frisbee on 2026-01-31T21:56:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'melted-frisbee'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 2
  memory_mb = 16000
